import glob
import os
from PIL import Image

label_counts = {
    "early": 0,
    "edo": 0,
    "golden": 0,
    "pre-meiji": 0,
    "meiji": 0,
    "modern": 0,
    "yokai": 0,
}

labels = {
    "early": ['okumura-masanobu',
            'hishikawa-moronobu',
            'torii-kiyomasu-ii',
            'nishikawa-sukenobu',
            'torii-kiyonobu-ii',
            'torii-kiyomasu-i',
            'nishimura-shigenaga',
            'torii-kiyonobu-i',
            'torii-kiyotada-i',
            'okumura-toshinobu'],
    "edo": ['katsukawa-shunsho',
            'suzuki-harunobu',
            'isoda-koryusai',
            'katsukawa-shunko',
            'katsukawa-shunei',
            'ippitsusai-buncho',
            'torii-kiyomitsu',
            'kitao-shigemasa',
            'utagawa-toyoharu',
            'ishikawa-toyonobu',
            'torii-kiyotsune',
            'torii-kiyohiro',
            'katsukawa-shunsen'],
    "golden": ['kitagawa-utamaro',
            'torii-kiyonaga',
            'toshusai-sharaku',
            'hosoda-eishi',
            'katsukawa-shuncho',
            'kubo-shunman',
            'eishosai-choki',
            'kitao-masayoshi',
            'katsukawa-shunzan',
            'chokosai-eisho',
            'utagawa-kunimasa',
            'ichirakutei-eisui'],
    "pre-meiji": ['utagawa-kunisada',
            'utagawa-hiroshige',
            'utagawa-kuniyoshi',
            'utagawa-toyokuni-i',
            'katsushika-hokusai',
            'utagawa-kunisada-ii',
            'utagawa-hiroshige-ii',
            'keisai-eisen',
            'utagawa-hirosada',
            'kikugawa-eizan',
            'totoya-hokkei',
            'utagawa-kuniyasu',
            'utagawa-kuniteru',
            'utagawa-kunikazu',
            'utagawa-yoshitsuya',
            'yashima-gakutei',
            'utagawa-yoshikazu',
            'utagawa-toyoshige',
            'utagawa-toyohiro',
            'utagawa-hirokage',
            'kano-shugen-sadanobu',
            'shunkosai-hokushu',
            'yoshifuji',
            'katsukawa-shuntei',
            'yanagawa-shigenobu',
            'gigado-ashiyuki',
            'hasegawa-sadanobu-i',
            'toyokawa-yoshikuni',
            'teisai-hokuba',
            'shotei-hokuju',
            'torii-kiyomine'],
    "meiji": ['toyohara-kunichika',
            'tsukioka-yoshitoshi',
            'toyohara-chikanobu',
            'ochiai-yoshiiku',
            'tsukioka-kogyo',
            'kobayashi-kiyochika',
            'utagawa-yoshitora',
            'mizuno-toshikata',
            'utagawa-yoshitaki',
            'utagawa-kunisada-iii',
            'ogata-gekko',
            'utagawa-hiroshige-iii',
            'morikawa-chikashige',
            'utagawa-sadahide',
            'kawanabe-kyosai',
            'utagawa-toyosai',
            'tomioka-eisen',
            'inoue-yasuji',
            'takeuchi-keishu',
            'adachi-ginko',
            'miyagawa-shuntei',
            'watanabe-nobukazu',
            'ikkei',
            'migita-toshihide',
            'shibata-zeshin',
            'utagawa-kuniaki',
            'imao-keinen',
            'kono-bairei',
            'kajita-hanko',
            'utagawa-kunimasa-iii',
            'torii-kiyosada',
            'watanabe-shotei',
            'utagawa-fusatane',
            'utagawa-kunitoshi',
            'seiko',
            'utagawa-yoshitoyo',
            'shibata-shinsai'],
    "modern": ['kawase-hasui',
            'tsuchiya-koitsu',
            'kasamatsu-shiro',
            'yoshida-hiroshi',
            'ito-shinsui',
            'ohara-koson',
            'fujishima-takeji',
            'takahashi-hiroaki',
            'hashiguchi-goyo',
            'wada-sanzo',
            'torii-kotondo',
            'shotei-takahashi',
            'koho',
            'yoshida-toshi',
            'shoson-ohara',
            'hasegawa-sadanobu-iii',
            'kaburagi-kiyokata',
            'onchi-koshiro',
            'natori-shunsen',
            'yamamoto-shoun',
            'maekawa-senpan',
            'henmi-takashi',
            'takehisa-yumeji',
            'okiie',
            'oda-kazuma',
            'asano-takeji',
            'tokuriki-tomikichiro',
            'nishijima-katsuyuki',
            'kawano-kaoru',
            'tom-kristensen',
            'maeda-masao',
            'ikeda-shuzo',
            'bakufu-ohno',
            'kotozuka-eiichi',
            'paul-binnie',
            'morozumi-osamu',
            'mitsuaki-sora',
            'okamoto-ryusei',
            'azechi-umetaro',
            'kitaoka-fumio',
            'hagiwara-hideo',
            'maki-haku',
            'inagaki-tomoo',
            'mabuchi-toru',
            'watanabe-sadao',
            'kusaka-kenji',
            'asai-kiyoshi',],
    "yokai": ["yokai"]
}

for f in glob.glob("jap-art/*/*.jpg"):
    img_name = f.split('/')[-1]
    artist_name = f.split('/')[-2]

    for (k, v) in labels.items():
        if artist_name in v:
            if not os.path.exists(f"jap-art/{k}"):
                os.makedirs(f"jap-art/{k}")
            label_counts[k] += 1

            image = Image.open(f)
            image.save(f"jap-art/{k}/{img_name}")
            os.remove(f)
            print(f)
            break

print(label_counts)
print(sum(label_counts.values()))